### ISSUE TITLE
752 - Cat in your code!

### ISSUE THREAD

**Issue by minajevs** [joho/7XX-rfc#167] opened 2016-01-22 11:15 UTC
Used when code accidentally replaced with emoji.

https://pbs.twimg.com/media/CLWSvZBUcAA9RIx.jpg reference

**Comment by nufrifin** [comment] 2016-12-20 18:03
Potentially duplicate of 732 - Fucking Unic💩de

**Comment by joho** [comment] 2016-12-20 22:59
Yup, dupe.

**Closed by joho** 2016-12-20 22:59 UTC
